name: Cd Pipeline

# Only trigger, when the build workflow succeeded
on:
    workflow_run:
        workflows: ["Ci Pipeline"]
        types:
            - completed

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: pull docker image
              run: sudo docker pull swistek/app1:latest
            - name: delete old docker image
              run: sudo docker rm -f app1-container || true
            - name: run docker container
              run: sudo docker run -d -p 8080:8080 --name app1-container swistek/app1
